# Generated by Django 4.2.7 on 2025-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('variator', 'CVT'), ('robot', 'Робот')], default='automatic', max_length=20),
        ),
    ]
